<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create viral shortclips image</name>
   <tag></tag>
   <elementGuidId>6c070da6-ccfc-4d8f-9fca-29f6f4cad0c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail.wp-image-9587</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/YT-IRL_Blog.jpg?resize=150%2C150&amp;ssl=1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Discovery Blog What is Eklipse.gg?Complete guide on how Eklipse can take your ch&quot;i >> img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1dfe4bb0-42b4-470e-877d-2b52f85cc26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>73096982-3ef1-41e6-bd08-75be5e7e2309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>e2710f84-0db8-4aea-bfa6-8d19fb55e5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>48e7217b-3435-44df-8ac2-9252929a5059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/YT-IRL_Blog.jpg?resize=150%2C150&amp;ssl=1</value>
      <webElementGuid>8646d562-40a4-46d3-aa23-dd67cf54e571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail wp-image-9587</value>
      <webElementGuid>61701b77-c165-425c-aab6-7970f10e0c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--center&quot;]/nav[@class=&quot;header-main__menu&quot;]/ul[@class=&quot;primary-menu&quot;]/li[@class=&quot;nav_item menu-item-depth-0 has-child menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children megamenu&quot;]/ul[@class=&quot;submenu submenu-lv1&quot;]/li[1]/div[@class=&quot;elementor elementor-3789&quot;]/div[@class=&quot;elementor-element elementor-element-2add0a43 e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-8f16397 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-fc034cf elementor-position-left elementor-position-top elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-vertical-align-top elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/img[@class=&quot;attachment-thumbnail size-thumbnail wp-image-9587&quot;]</value>
      <webElementGuid>176add36-2dc5-494f-af0e-8493da2dc4f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/YT-IRL_Blog.jpg?resize=150%2C150&amp;ssl=1')]</value>
      <webElementGuid>e717e574-d218-4f98-abd5-4a1d2775ed47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/figure/img</value>
      <webElementGuid>f4b717d2-98ef-47e3-af35-116845a52c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/YT-IRL_Blog.jpg?resize=150%2C150&amp;ssl=1']</value>
      <webElementGuid>33d8aa7c-26c9-4ddf-b560-e09c76d72989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
