<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Eklipse.gg text</name>
   <tag></tag>
   <elementGuidId>a473d453-9ad1-4d3a-b973-67c9262e4a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trust-display-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='trust-display-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Eklipse.gg&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c4d0640c-6d85-47b0-a097-6227285c3443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trust-display-name</value>
      <webElementGuid>0404e9bd-cfcf-4380-b241-6a2be78cdca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-dark</value>
      <webElementGuid>88c201ea-0e43-4cde-a806-8783ef53de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eklipse.gg</value>
      <webElementGuid>0ef7e65e-ec48-4631-893b-e2232f613d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trust-display-name&quot;)</value>
      <webElementGuid>580dfe38-2ec1-4383-9884-635556c63965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='trust-display-name']</value>
      <webElementGuid>50973a8d-2d6c-49b5-b27e-2593c97db046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn Premium'])[1]/following::h3[1]</value>
      <webElementGuid>59cc186e-a158-4281-a467-bdef5bf1c749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start for Free'])[1]/following::h3[1]</value>
      <webElementGuid>ca8f18be-90f3-4c46-8c4e-0f3c05785ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Built for everyone, every creator'])[1]/preceding::h3[1]</value>
      <webElementGuid>78cc3cae-26ac-4776-bc78-7a61db001019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eklipse.gg']/parent::*</value>
      <webElementGuid>6ec0d7cd-5ee2-4a6a-8996-76c8b7c5acfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[3]/div/div/div/h3</value>
      <webElementGuid>489293c6-6cef-4ff4-85e3-76afb16e75d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'trust-display-name' and (text() = 'Eklipse.gg' or . = 'Eklipse.gg')]</value>
      <webElementGuid>043c21fa-8037-4c55-b53d-ca9151c57bec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
