<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>9602d235-74f1-4408-8856-0104fb2cb63e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Eklipse: AI-Edit - Enhance your gaming clips with memes, sfx, vfx in seconds | Product Hunt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-9380']/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Eklipse: AI-Edit - Enhance your gaming clips with memes, sfx, vfx in seconds | Product Hunt&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9240c2c7-61f6-4546-bec1-bca82f1e2f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=457938&amp;theme=light</value>
      <webElementGuid>40f9214b-8bd9-4e3b-905b-56c5cb25190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eklipse: AI-Edit - Enhance your gaming clips with memes, sfx, vfx in seconds | Product Hunt</value>
      <webElementGuid>26ebfff7-64ff-4951-889b-24e821bba297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>19fadb80-fccd-42ff-a27b-4fb58b6988be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>48efd257-194d-4cfb-807f-112f9eddfaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-9380&quot;)/a[2]/img[1]</value>
      <webElementGuid>ccc36117-8506-4422-9f1b-5c92ee723adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-9380']/a[2]/img</value>
      <webElementGuid>6fab8fdb-6660-47d7-80a0-a1d6d8ef9277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eklipse: AI-Edit - Enhance your gaming clips with memes, sfx, vfx in seconds | Product Hunt']</value>
      <webElementGuid>38feecdf-a7eb-4dcc-91fd-5355a3e5f08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>9af63cda-a4e6-4bd5-bc1b-8ba74975df4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=457938&amp;theme=light' and @alt = 'Eklipse: AI-Edit - Enhance your gaming clips with memes, sfx, vfx in seconds | Product Hunt']</value>
      <webElementGuid>b8cc12d0-f938-43a5-baa2-38d5c8e0fb93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
