<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reviews 389 image</name>
   <tag></tag>
   <elementGuidId>5a1eb690-18b0-4efc-a531-8afc44a78134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trust-img-starts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='trust-img-starts']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;TrustScore 4.5 out of 5&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8949380a-a9fa-43eb-ac29-23b75b264ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>31cb2cd1-f408-431d-8ba5-2af3c774558b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trust-img-starts</value>
      <webElementGuid>e50cdd59-7b12-4d0b-bf47-d22147f9fb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TrustScore 4.5 out of 5</value>
      <webElementGuid>1f59b8ba-a593-484b-b444-5635bea48d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-4.5.svg</value>
      <webElementGuid>0413c76f-2418-4e51-8b87-e08f03c3dd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trust-img-starts&quot;)</value>
      <webElementGuid>8dda361f-a69d-4903-b743-2901af1f05b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='trust-img-starts']</value>
      <webElementGuid>557052f6-e734-4aa5-9afc-654fbb360a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TrustScore 4.5 out of 5']</value>
      <webElementGuid>4b811008-7580-43c6-8c91-5857790d96fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>e92cd9d7-5659-467e-afc9-49bc57edf1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'trust-img-starts' and @alt = 'TrustScore 4.5 out of 5' and @src = 'https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-4.5.svg']</value>
      <webElementGuid>c1e9864a-cd04-4a8e-bd4e-fe5018285bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
