<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video Reviews 389 div</name>
   <tag></tag>
   <elementGuidId>73f4b3e5-6b17-419e-a3b5-d04b71f40322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.elementor-element.elementor-element-b0ff75c.e-con-full.e-flex.e-con.e-child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Eklipse.gg'])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main > div > div > div:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0e0f2a9-3dd8-4383-8b21-ec8acd694023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-element elementor-element-b0ff75c e-con-full e-flex e-con e-child</value>
      <webElementGuid>697bd78a-b01f-408c-9b5e-9adbc5c77b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>b0ff75c</value>
      <webElementGuid>089c8c1a-cd60-4c2e-93e7-1d10d2499b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element_type</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>55eda7ab-4c5d-4c07-8abd-30594c67e577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-settings</name>
      <type>Main</type>
      <value>{&quot;background_background&quot;:&quot;classic&quot;}</value>
      <webElementGuid>88decb0b-58c3-4100-ab71-1b6b57275e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/main[1]/div[@class=&quot;elementor elementor-13271&quot;]/div[@class=&quot;elementor-element elementor-element-6e1f56c e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-b0ff75c e-con-full e-flex e-con e-child&quot;]</value>
      <webElementGuid>3883ab59-c976-44f5-aeac-ed0f975ad217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eklipse.gg'])[1]/following::div[3]</value>
      <webElementGuid>1e2c1191-196e-42bc-bd29-fc4b1fa7b689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Built for everyone, every creator'])[1]/preceding::div[8]</value>
      <webElementGuid>673cd507-8a93-436c-81a9-991609a9a7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compatible with any console'])[1]/preceding::div[15]</value>
      <webElementGuid>f092a646-9c4d-4a8f-882c-9ad2c85f1f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]</value>
      <webElementGuid>e8760520-a992-448a-9451-52ef5110e94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
