<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Copyright</name>
   <tag></tag>
   <elementGuidId>19121c22-78f3-4400-b085-2b8efd114ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@class = 'text-muted' and (text() = 'Copyright © CURA Healthcare Service 2024' or . = 'Copyright © CURA Healthcare Service 2024')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5b04ec2a-209f-49d4-a2f2-08a8a0c74404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-muted</value>
      <webElementGuid>924504ff-d3d2-4973-b5bd-70cfd2eb21b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copyright © CURA Healthcare Service 2024</value>
      <webElementGuid>934c5cd4-f666-4910-a66a-bb0c51e5ae80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
