<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Visit date_switch</name>
   <tag></tag>
   <elementGuidId>a6a9cce3-e3f2-4cef-a13b-243684edf728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[@colspan = '5' and @class = 'datepicker-switch' and (text() = 'July 2024' or . = 'July 2024')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/table/thead/tr[2]/th[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>22e10a1a-9e93-4a14-8a67-150287ec3877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5c25a840-60b1-4ccd-a08b-07b952fc3668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-switch</value>
      <webElementGuid>74297892-2c17-40f3-8f5a-4528f521b0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>July 2024</value>
      <webElementGuid>06146a92-f5d4-48fe-9697-c73a7d7e1db2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
