<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Visit date_previous</name>
   <tag></tag>
   <elementGuidId>b6542bbb-3bac-4544-b13c-f70138901a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[@class = 'prev' and @style = 'visibility: visible;' and (text() = '«' or . = '«')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/table/thead/tr[2]/th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>455b7aeb-61f7-4d1e-8d51-7831b400cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>745b430c-45a8-42c4-9dbf-0bf163485d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>visibility: visible;</value>
      <webElementGuid>b5fabbe8-a3ab-447d-916a-d192c937060c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>«</value>
      <webElementGuid>08b1ccc9-2c13-4b11-9775-b06664eb0ac6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
