<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request Edit Now</name>
   <tag></tag>
   <elementGuidId>13d19b89-201d-4f76-a3c9-36d86903ac60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[48]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ek-primary-button.mt-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Request Edit Now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d04ab645-d804-4422-8035-2c6e4a6920dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21e09908-042b-42b5-a57d-dc2ced58c94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>12db7e91-6b42-41a5-b34a-86a77e25d280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#requestPremiumEditing</value>
      <webElementGuid>5a2f20d3-85c9-47c3-82cb-c9320d3ffab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-backdrop</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>73a2b5e6-544f-4c83-9731-ff88f73ede39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keyboard</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59c9f2ef-afd8-4038-9c19-f06e3faa0367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-primary-button mt-4</value>
      <webElementGuid>2d800997-c32a-4926-8ac7-4665146972d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request Edit Now</value>
      <webElementGuid>4ffe68e7-65b4-40f0-9634-d865b4ce18a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-edited-video ek-pro-clips-page&quot;]/div[1]/div[@class=&quot;fluid-container form-input-detail mt-4 no-premium-clip&quot;]/div[@class=&quot;form-input-detail-row end&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-6 col-sm-12 mt-md-0 mt-4 text-center text-sm-left&quot;]/button[@class=&quot;ek-primary-button mt-4&quot;]</value>
      <webElementGuid>76096231-e9d6-49ea-81df-9de975234ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[48]</value>
      <webElementGuid>6c07beca-e759-4398-aba2-bd4919d9d024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div/div[3]/div/div/div[2]/button</value>
      <webElementGuid>9ccd690f-27fa-41ef-91ed-49039160b458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@DundunemallTwitch Streamer'])[3]/following::button[5]</value>
      <webElementGuid>9abb5b63-b6c7-42b1-8647-0709ccc1aff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omg the clips.is awsome thank you so much'])[3]/following::button[5]</value>
      <webElementGuid>edc9293f-609a-4814-bb99-a295692a706b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Pro Edits'])[1]/preceding::button[1]</value>
      <webElementGuid>451fb18c-c0dc-45b3-93fc-f6b588a26bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total duration'])[1]/preceding::button[2]</value>
      <webElementGuid>50e1a873-f6bd-49e0-a2f6-939f44d83dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request Edit Now']/parent::*</value>
      <webElementGuid>f19fc122-59e6-425c-81da-8d20faf7fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/button</value>
      <webElementGuid>9fbf48b0-acc9-4ae7-bf9a-8b3dec4b570b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Request Edit Now' or . = 'Request Edit Now')]</value>
      <webElementGuid>57a5cabb-8d33-4d21-9687-5c9784e0acdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
