<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Show off your content</name>
   <tag></tag>
   <elementGuidId>8eb5d7b3-3199-4120-a16e-78e2e1bbc996</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div/div[3]/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Show off your content with pro-quality editing to your social media!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>00bb1540-02d5-41fc-aab8-f2965a2a4ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary</value>
      <webElementGuid>bcbdf122-dcb7-4be7-be57-cc7a51ca1efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show off your content with pro-quality editing to your social media!</value>
      <webElementGuid>1742006a-28a8-4b40-a409-4550f6e973e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-edited-video ek-pro-clips-page&quot;]/div[1]/div[@class=&quot;fluid-container form-input-detail mt-4 no-premium-clip&quot;]/div[@class=&quot;form-input-detail-row end&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-6 col-sm-12 mt-md-0 mt-4 text-center text-sm-left&quot;]/p[@class=&quot;text-secondary&quot;]</value>
      <webElementGuid>4ce2b6bf-2863-4555-a7bd-38c310468c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div/div[3]/div/div/div[2]/p</value>
      <webElementGuid>1197a98f-0738-4000-9279-bcba5f14a789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give a Pro-Quality Editing to Your Clips'])[1]/following::p[1]</value>
      <webElementGuid>0354bea4-43f1-46a6-a0c6-85add1710b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Sample Videos'])[1]/following::p[1]</value>
      <webElementGuid>a78156da-41d7-43f3-b986-8bb0fb190a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omg the clips.is awsome thank you so much'])[1]/preceding::p[1]</value>
      <webElementGuid>0af60e08-ae53-4659-bfd4-1628c988ad45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@DundunemallTwitch Streamer'])[1]/preceding::p[1]</value>
      <webElementGuid>eebd59e8-06b2-48af-8209-e7c7be463fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show off your content with pro-quality editing to your social media!']/parent::*</value>
      <webElementGuid>ecd9802d-48d7-4fb6-aef4-25370aae3a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>40b1c7fa-965a-43e3-bc35-5c6b0812fce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Show off your content with pro-quality editing to your social media!' or . = 'Show off your content with pro-quality editing to your social media!')]</value>
      <webElementGuid>54a3e708-1463-4da6-b432-36bfabb36295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
