<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Zoom</name>
   <tag></tag>
   <elementGuidId>c9ce3c27-4390-4652-888a-f5d1aafaa9cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step2']/div/div[4]/div/div/div/label/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Zoom&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16918de1-d06c-40f5-9b80-5363e4d8ff3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>1e0743fe-eab5-4c16-9689-25c68938adf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zoom</value>
      <webElementGuid>1ca7ce09-54a6-4b6e-aea0-6406234a0575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step2&quot;)/div[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;checkbox-section checkbox-section-sm&quot;]/label[@class=&quot;ipt-label sm&quot;]/span[@class=&quot;content&quot;]</value>
      <webElementGuid>f62e46a8-3be7-42ea-9e9a-ad05e8732718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step2']/div/div[4]/div/div/div/label/span[2]</value>
      <webElementGuid>b39a6728-0e2d-4e61-8438-444cb46c5a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[2]</value>
      <webElementGuid>12fb9fd4-b6f9-42ab-ab17-f1e2c80723c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effect Options'])[1]/following::span[3]</value>
      <webElementGuid>d02adbdd-25fe-4adf-91b0-871501653c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtitles'])[1]/preceding::span[2]</value>
      <webElementGuid>093ec36a-deda-4c32-afb4-d98f504ff4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English only'])[1]/preceding::span[3]</value>
      <webElementGuid>0c058e8b-190e-4720-b57b-6d3a223f90af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zoom']/parent::*</value>
      <webElementGuid>cbde4b61-6789-49c7-a6ac-b61bd612b909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/label/span[2]</value>
      <webElementGuid>ace5fc36-3f19-45a8-9181-073b5038d057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Zoom' or . = 'Zoom')]</value>
      <webElementGuid>baafd2f0-57e4-44a0-bd75-3b5ac4f52b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
