<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4.7 text</name>
   <tag></tag>
   <elementGuidId>6e8b565f-f0bd-4e0d-b8ae-9b78e4248001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trust-scores</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='trust-scores']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;4.7&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0162cd79-4ab8-43e2-9ae6-ec6231e5ce58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trust-scores</value>
      <webElementGuid>ac27393b-02f7-4322-9d58-ceb17baf617b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4.7</value>
      <webElementGuid>30434c3c-b171-49fd-bdcc-fbc4dc6ae3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trust-scores&quot;)</value>
      <webElementGuid>30bb5638-10f2-4320-bd4e-debcbf86b550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='trust-scores']</value>
      <webElementGuid>ff6ed8cf-88c2-4a10-8639-9a36cd1ebba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eklipse.gg'])[1]/following::span[1]</value>
      <webElementGuid>b71f8626-4cb7-477e-8532-f2c855c32bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Built for everyone, every creator'])[1]/preceding::span[1]</value>
      <webElementGuid>e4c0ddca-20e0-41e4-be56-f18c98beb554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compatible with any console'])[1]/preceding::span[1]</value>
      <webElementGuid>ceee6b17-83bc-4771-950f-ddaf2b93f2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4.7']/parent::*</value>
      <webElementGuid>bae47807-e9d6-48d6-a1b8-4f8e849f9720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>8443feb2-0133-45ed-8836-238f4cc63302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'trust-scores' and (text() = '4.7' or . = '4.7')]</value>
      <webElementGuid>6b0b8ec7-670c-42aa-8a14-49accb3c5705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
