<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Content publisher image</name>
   <tag></tag>
   <elementGuidId>1ce2d52a-cfbb-4349-93d1-ff942d7dd03a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail.wp-image-12004</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Content-Publisher_150px.png?resize=150%2C150&amp;ssl=1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) > .elementor-widget-container > .elementor-image-box-wrapper > .elementor-image-box-img > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cbbadb9d-5251-4c8b-af16-e17159308fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e09fe92b-d7d8-4f57-8f26-6fd114ae0e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>1cc3330a-0bd6-44d4-a3d5-f954c903e9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>732d1265-1ebf-4fdb-967a-34f4bef4e3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Content-Publisher_150px.png?resize=150%2C150&amp;ssl=1</value>
      <webElementGuid>3f75de9f-3448-4fdb-bfa4-b0688026b121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail wp-image-12004</value>
      <webElementGuid>d482e593-5ce3-4880-a93c-c4a2b7f32f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--center&quot;]/nav[@class=&quot;header-main__menu&quot;]/ul[@class=&quot;primary-menu&quot;]/li[@class=&quot;nav_item menu-item-depth-0 has-child menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children megamenu&quot;]/ul[@class=&quot;submenu submenu-lv1&quot;]/li[1]/div[@class=&quot;elementor elementor-11934&quot;]/div[@class=&quot;elementor-element elementor-element-e79b4d5 e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-8f4d5bc e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-d94e4cb e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-1c0d477 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-719770b elementor-position-left elementor-position-left elementor-vertical-align-middle elementor-widget__width-initial elementor-widget-mobile__width-initial elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/a[1]/img[@class=&quot;attachment-thumbnail size-thumbnail wp-image-12004&quot;]</value>
      <webElementGuid>a688b77e-2271-4405-a52d-8ffcaff07428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Content-Publisher_150px.png?resize=150%2C150&amp;ssl=1')]</value>
      <webElementGuid>3ef7f7f3-409c-42d3-a734-0e57de80056e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/figure/a/img</value>
      <webElementGuid>7b9ecb95-26f8-422b-ab37-f60b51760c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Content-Publisher_150px.png?resize=150%2C150&amp;ssl=1']</value>
      <webElementGuid>c6adee8f-ee68-4e05-8d3a-fba4ab25040a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
