<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>for everyone image</name>
   <tag></tag>
   <elementGuidId>76fc8cd3-fa68-43c3-bd6f-293c0395749f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?resize=150%2C150&amp;ssl=1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail.wp-image-3984</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.elementor-widget-container > .attachment-thumbnail >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b56a41e2-8488-4704-a11a-a14e9374bd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b745a8d0-b4b7-4929-8190-df1350070e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c2ea385d-f97e-4923-a6b4-45017ba291c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3a8d84e8-b090-40ae-ad04-464466fa8110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3248ad4d-98da-473d-a26e-3573083c6483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?resize=150%2C150&amp;ssl=1</value>
      <webElementGuid>f37d86d9-9574-4f23-9fe8-fcb42ea39af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail wp-image-3984</value>
      <webElementGuid>266654cf-2992-47be-9d73-4f4fb35a692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?w=341&amp;ssl=1 341w, https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?resize=300%2C300&amp;ssl=1 300w, https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?resize=150%2C150&amp;ssl=1 150w</value>
      <webElementGuid>02b758c8-edce-4fd1-b1d1-cbd21c27ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 150px) 100vw, 150px</value>
      <webElementGuid>fdc95c5e-44e2-4a17-822e-bc9893eb7950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/main[1]/div[@class=&quot;elementor elementor-13271&quot;]/div[@class=&quot;elementor-element elementor-element-72efe6c1 e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-f7ded87 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-6d4aed1 elementor-widget-mobile__width-auto elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-thumbnail size-thumbnail wp-image-3984&quot;]</value>
      <webElementGuid>0b9591cd-0056-439c-a356-1d60190dcf81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?resize=150%2C150&amp;ssl=1')]</value>
      <webElementGuid>42153987-225b-4770-bb38-9175c7a4258a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>a5b89591-27e8-4264-adde-a8e4b0194d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/ic_eklipse.png?resize=150%2C150&amp;ssl=1']</value>
      <webElementGuid>f1852135-b5fe-4fc6-804d-b5d5e269672d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
