<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>How Clip Automatically</name>
   <tag></tag>
   <elementGuidId>479838f6-329f-48f9-af05-7b007a8364b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='elementor-tab-title-1155']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1155 > a.elementor-accordion-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;How to Clip Kick Stream Automatically with AI?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99574a30-3c55-4079-bad9-e782fce2af43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-accordion-title</value>
      <webElementGuid>53ff2bfd-7174-478e-9406-428fad010f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>621ed1bc-26cd-4a97-bbd6-48e35c47b5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to Clip Kick Stream Automatically with AI?</value>
      <webElementGuid>32f33ee6-7a8b-4e14-bcdf-33d883c9e785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1155&quot;)/a[@class=&quot;elementor-accordion-title&quot;]</value>
      <webElementGuid>368c0eaa-30ce-40ae-ab8d-953cf61655ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='elementor-tab-title-1155']/a</value>
      <webElementGuid>f00c4f21-a406-4b36-ab53-bff0f0281fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'How to Clip Kick Stream Automatically with AI?')]</value>
      <webElementGuid>17e9d8e3-171f-415f-b28f-3384671bea56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a final touch to your clip, hit “Confirm” when you’re done'])[1]/following::a[1]</value>
      <webElementGuid>c1fc0caf-e36b-484a-9389-255803bb9701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a template and edit your layer for facecam and gameplay.'])[1]/following::a[1]</value>
      <webElementGuid>a4444338-45ad-4f31-8f65-84372200d561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up and create your Eklipse account'])[1]/preceding::a[1]</value>
      <webElementGuid>a88a5c95-3e85-48b5-ae03-8b7cbf036af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='How to Clip Kick Stream Automatically with AI?']/parent::*</value>
      <webElementGuid>290a2373-37cb-45c8-b306-b9fa017068f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/h2/a</value>
      <webElementGuid>2e87ae5c-f1b2-4e19-8b03-858a2ac166d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'How to Clip Kick Stream Automatically with AI?' or . = 'How to Clip Kick Stream Automatically with AI?')]</value>
      <webElementGuid>5cc463de-1516-4930-acca-d377c6af3b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
