<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kick support image</name>
   <tag></tag>
   <elementGuidId>e9dcf0c2-d967-4d23-b68f-35b6cb6f393b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail.wp-image-12006</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Kick-Support_150px.webp?resize=150%2C150&amp;ssl=1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > div:nth-child(2) > .elementor-widget-container > .elementor-image-box-wrapper > .elementor-image-box-img > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7a2fb885-5611-4f9f-8d17-b5c7bb556be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fd54d2c7-ab6d-4fc2-aa5e-efe30c3ca356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>ea50be91-91a5-4a77-ba82-94dea3722596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>c15b0ce3-d9c3-4a20-adb9-9b812923c90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Kick-Support_150px.webp?resize=150%2C150&amp;ssl=1</value>
      <webElementGuid>dadeff38-2405-40f8-9dd2-27f0b4f7c8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail wp-image-12006</value>
      <webElementGuid>4851d4a9-b300-4158-820a-11ef82fe1804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--center&quot;]/nav[@class=&quot;header-main__menu&quot;]/ul[@class=&quot;primary-menu&quot;]/li[@class=&quot;nav_item menu-item-depth-0 has-child menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children megamenu&quot;]/ul[@class=&quot;submenu submenu-lv1&quot;]/li[1]/div[@class=&quot;elementor elementor-11934&quot;]/div[@class=&quot;elementor-element elementor-element-e79b4d5 e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-28817fa e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-653a68f e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-c9d9968 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-25e305d elementor-position-left elementor-position-top elementor-widget-mobile__width-initial elementor-vertical-align-top elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/a[1]/img[@class=&quot;attachment-thumbnail size-thumbnail wp-image-12006&quot;]</value>
      <webElementGuid>830b7cc0-575c-45e1-9dbc-0269c3db866b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Kick-Support_150px.webp?resize=150%2C150&amp;ssl=1')]</value>
      <webElementGuid>7691f7d8-f94f-432d-a5ad-ddc550558447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/figure/a/img</value>
      <webElementGuid>4dd8ff4d-5e5d-4709-9a76-59da076ca627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Kick-Support_150px.webp?resize=150%2C150&amp;ssl=1']</value>
      <webElementGuid>fc60d9bd-1644-4470-9910-759b92518e7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
