<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get clip (1)</name>
   <tag></tag>
   <elementGuidId>ed183df8-0916-4df8-828c-e610b768438b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[50]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-slide.slick-active.slick-current > div > div.d-flex.gap-2 > div.sample-card > button.ek-secondary-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Get clip&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2dd54681-facc-406e-8e4d-88c0730c8f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>294637d3-36b3-4309-99f8-3e314d757b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-secondary-button</value>
      <webElementGuid>e4534b34-030d-4dbc-a9e2-d2dba0103183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get clip</value>
      <webElementGuid>34e35cbb-70c4-4b3e-a4b1-da9576aa1459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-dashboard__home&quot;]/div[@class=&quot;ek-stream-list&quot;]/div[@class=&quot;import-video-container d-flex flex-column justify-content-center align-items-center&quot;]/div[4]/div[@class=&quot;slick-slider stream-library-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;d-flex gap-2&quot;]/div[@class=&quot;sample-card&quot;]/button[@class=&quot;ek-secondary-button&quot;]</value>
      <webElementGuid>74fff1c2-f86a-47a3-9053-c48dd0583c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[50]</value>
      <webElementGuid>703eeb6c-002b-4fe2-b723-bce44c75cdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div[3]/div/div[4]/div/div/div/div[3]/div/div/div/button</value>
      <webElementGuid>8727bbb1-835d-46f9-a1ab-d25ee87ffc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get clip'])[7]/following::button[1]</value>
      <webElementGuid>94dec2fc-b83a-45a0-a7a8-52ed6f945560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get clip'])[6]/following::button[2]</value>
      <webElementGuid>fb729e59-8816-481f-8b93-c078b08e3b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get clip'])[9]/preceding::button[1]</value>
      <webElementGuid>4277f566-334c-483b-aed7-5b70271582ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get clip'])[10]/preceding::button[2]</value>
      <webElementGuid>2de07e63-40e7-47cb-8680-0e9a19de6a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[3]/div/div/div/button</value>
      <webElementGuid>af1b6f24-d7ac-44fa-905d-987863b38221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Get clip' or . = 'Get clip')]</value>
      <webElementGuid>d2eb1b59-ef01-4ab8-baee-9bc8c9895cec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
