<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_New to Eklipse Try</name>
   <tag></tag>
   <elementGuidId>fa852460-18e1-45e9-82bc-724ee2c8921e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div[3]/div/div[4]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.mb-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;New to Eklipse? Try our AI withcontent!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2dcfa6b2-7e5f-486e-8fde-7e3f277be203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>3d9b3e50-ebc3-4f72-a961-7823f07934dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New to Eklipse? Try our AI withcontent!</value>
      <webElementGuid>79f796a1-c38f-4d3b-8186-dfef367972a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-dashboard__home&quot;]/div[@class=&quot;ek-stream-list&quot;]/div[@class=&quot;import-video-container d-flex flex-column justify-content-center align-items-center&quot;]/div[4]/p[@class=&quot;mb-1&quot;]</value>
      <webElementGuid>9034b467-8248-4fcc-94bb-6502a4425ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div[3]/div/div[4]/p</value>
      <webElementGuid>49c59a93-7f80-40e1-96c0-d5bfffde5ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get highlights from your gaming stream on the ‘Live Stream’ tab.'])[3]/following::p[1]</value>
      <webElementGuid>685d4051-afdd-4ab3-a19c-f425a49d7fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get clip'])[1]/preceding::p[2]</value>
      <webElementGuid>cf02d9dd-b581-46c1-bd54-426023d1655c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New to Eklipse? Try our AI with']/parent::*</value>
      <webElementGuid>dc3369e0-37ec-4c3d-a797-ff3f3e233792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p</value>
      <webElementGuid>0b75aa56-e847-4e3d-b553-fd5733ada10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'New to Eklipse? Try our AI withcontent!' or . = 'New to Eklipse? Try our AI withcontent!')]</value>
      <webElementGuid>7aa642a9-8c89-448d-9e8d-18b478ffbabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
