<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Automate highlights Mark</name>
   <tag></tag>
   <elementGuidId>45b02945-6882-4a18-8ce3-fb3cd3ea8f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Automate highlights from Twitch, YouTube, and Kick livestreams\.$/ >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>194e301d-b26b-4ccb-8461-bee38b6922ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/svg/ic-check.svg</value>
      <webElementGuid>4db7d936-f3c2-4a7a-b977-93594ce32a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>ec891b21-754d-49a2-860b-ca5c27135ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>611dbb58-a125-4b6c-a627-4ee6e2082f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>34dee5c2-bc2e-430d-96cb-883719891d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;page-auth v2&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;section-info d-none d-lg-block col-lg-6 p-0&quot;]/div[@class=&quot;auth-message&quot;]/div[@class=&quot;message-container d-flex flex-column&quot;]/div[@class=&quot;description d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/img[@class=&quot;mr-2&quot;]</value>
      <webElementGuid>bdaad647-4c38-4739-9247-13c62655e4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div[2]/div/img</value>
      <webElementGuid>fffc4b4f-d4f6-4215-b153-8a52941f06fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>c93e1584-7578-479b-b432-0600f39d34ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/svg/ic-check.svg']</value>
      <webElementGuid>65ec02bb-a670-4407-8d0b-ed9064be0b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
