<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reject</name>
   <tag></tag>
   <elementGuidId>692af620-aa9b-40c7-ac40-0107685529da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cookie-btn > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='rejectCookie();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reject&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e51b056-5fb2-42ed-acfd-6bb1644b7088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>rejectCookie();</value>
      <webElementGuid>fe6bbe3f-775b-478d-b79c-48cfe71fdbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Reject
                    </value>
      <webElementGuid>c32637e9-6bcd-49cc-b69b-32c1e91aea89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookie-notice&quot;)/div[@class=&quot;light display-right&quot;]/div[@class=&quot;cookie-content&quot;]/div[@class=&quot;cookie-msg&quot;]/div[@class=&quot;cookie-btn&quot;]/button[1]</value>
      <webElementGuid>2001f90d-8769-4c35-ab69-49d968009cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='rejectCookie();']</value>
      <webElementGuid>8182d692-2b6a-408a-9f3a-f912a3499053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-notice']/div/div[3]/div/div[2]/button</value>
      <webElementGuid>d7718507-be6e-46fb-93dd-618a9b680f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::button[1]</value>
      <webElementGuid>af8be373-38d4-4f4d-9a91-e9ad7e75db9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Consent'])[1]/following::button[1]</value>
      <webElementGuid>3137985e-5d52-40f9-8c4d-1364b50cf382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept'])[1]/preceding::button[1]</value>
      <webElementGuid>8b2739f4-b9dd-4c4a-9c21-96addc4d31ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reject']/parent::*</value>
      <webElementGuid>26d8b5a9-6a3d-4a0a-91c7-eeb05daf9600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>c01b7801-dd56-499e-94a7-63e7f9563165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                        Reject
                    ' or . = '
                        Reject
                    ')]</value>
      <webElementGuid>b64f4ab1-4bd6-41b9-9de1-7da066d48d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
