<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit highlight Mark</name>
   <tag></tag>
   <elementGuidId>c10df51d-43fe-4341-9e93-3cbc28b4d6ba</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div[2]/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Edit highlights into shareable clips instantly with AI-Edit\.$/ >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>087f0889-a714-4446-ab35-622984ad30cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/svg/ic-check.svg</value>
      <webElementGuid>0650a5b4-674f-4525-bffc-922ab404b2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>09ef6cdc-8d23-40e4-8235-fa5b0e86baf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>bed8fc85-6ee6-40de-8ac2-9a001e0ba2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>2881715e-ec59-4488-af8f-fe7c5d2c97cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;page-auth v2&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;section-info d-none d-lg-block col-lg-6 p-0&quot;]/div[@class=&quot;auth-message&quot;]/div[@class=&quot;message-container d-flex flex-column&quot;]/div[@class=&quot;description d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/img[@class=&quot;mr-2&quot;]</value>
      <webElementGuid>022f41cf-7fb4-4de9-ae45-579e5b6f37c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div[2]/div[2]/img</value>
      <webElementGuid>d87067d2-1d80-4e25-bb99-ccd5ba25ade9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>279bbdd6-26de-4936-8df1-b6224ce854f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/svg/ic-check.svg']</value>
      <webElementGuid>c1b3a83c-fe8d-4b1d-92e4-9d9ea2ff4e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
