<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Eklipse gg image_Left</name>
   <tag></tag>
   <elementGuidId>07b42292-855c-44aa-83f4-c5e86f1937ed</elementGuidId>
   <imagePath>../../OneDrive/Dokument/Tita/Lamaran kerja/Eklipse.gg/Eklipse gg image_Left.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../OneDrive/Dokument/Tita/Lamaran kerja/Eklipse.gg/Eklipse gg image_Left.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad8b42db-2594-4ebf-84f9-b4731d83f8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo-eklipse.png</value>
      <webElementGuid>9893914a-c64e-4701-aa55-5e94b99f1399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>9241ead9-43cf-4bdd-9bd0-f96294b3133d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;page-auth v2&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;section-info d-none d-lg-block col-lg-6 p-0&quot;]/div[@class=&quot;auth-message&quot;]/div[@class=&quot;message-container d-flex flex-column&quot;]/div[1]/img[1]</value>
      <webElementGuid>1ea87e70-5a25-4677-9693-9616cf6fdee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/img</value>
      <webElementGuid>be74e96c-1f5b-4237-85b5-a0bd151af395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>c6f743ac-95bd-4741-8cbd-4409b26a91b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9556768c-3f69-4558-a038-cb474c6f920a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/logo-eklipse.png' and @alt = 'logo']</value>
      <webElementGuid>02a0a780-c388-48a7-aeed-75b6a7364d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
