<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edited Clips</name>
   <tag></tag>
   <elementGuidId>f79b6765-7364-4caa-81cd-3ba59448ae98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submenu-3']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submenu-3 > ul > li:nth-of-type(2) > a.sidebar-submenu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Edited Clips&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>164b2df5-efcf-4060-ac80-c96817ecfb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-submenu-link</value>
      <webElementGuid>cc51aad2-664d-4206-ba77-3512f7374195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edited-clip/edited-by-you</value>
      <webElementGuid>a2097f27-917c-4b9e-80ae-0a58a9183b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edited Clips</value>
      <webElementGuid>5fba1776-6d0a-4174-9649-4d4af86873c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-3&quot;)/ul[1]/li[2]/a[@class=&quot;sidebar-submenu-link&quot;]</value>
      <webElementGuid>2fa255ea-df26-4a0d-bb38-07448bc252b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submenu-3']/ul/li[2]/a</value>
      <webElementGuid>9ab2818b-ed0e-45f4-9635-c2ef8c7f7012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::a[1]</value>
      <webElementGuid>6f5246fe-845b-4dd2-9718-b12e475ba307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI Edit'])[1]/following::a[1]</value>
      <webElementGuid>134c8efd-67bf-4b36-b806-db277a6c67b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montages'])[1]/preceding::a[1]</value>
      <webElementGuid>eea3d07d-d910-4c87-9fa2-be9f8ab6ab8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edited-clip/edited-by-you')]</value>
      <webElementGuid>b1d5ac60-e8d5-41e6-9b5b-1edccad48c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/ul/li[2]/a</value>
      <webElementGuid>65893d9c-48d7-47e0-baac-3d93ba634947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edited-clip/edited-by-you' and (text() = 'Edited Clips' or . = 'Edited Clips')]</value>
      <webElementGuid>2b1142e7-2e37-4924-845d-bc637a943054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
