<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create AI Edit</name>
   <tag></tag>
   <elementGuidId>f294caa8-922d-4dbc-82aa-fb19af3ac3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-ai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create AI Edit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd12c2e1-30d4-4827-b481-b5582fd09da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-ai</value>
      <webElementGuid>79560c88-156c-4d0b-ace9-8796f68d0394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create AI Edit</value>
      <webElementGuid>bde53480-34cd-4d66-b186-fa09497db235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-ai-edit&quot;]/div[@class=&quot;page-description d-flex mb-2&quot;]/div[@class=&quot;d-flex btn-container&quot;]/div[@class=&quot;btn-ai&quot;]</value>
      <webElementGuid>edda2465-11fb-4620-b9ca-e07e4d354a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>5fb5df97-2d3f-4e49-8736-611cfad62dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try AI Edit on Discord'])[1]/following::div[1]</value>
      <webElementGuid>fb403fd5-0a38-4c33-8ea7-f51b60eab1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI Edit'])[2]/following::div[3]</value>
      <webElementGuid>fadff800-4807-4f95-97dc-c28284acb116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/preceding::div[1]</value>
      <webElementGuid>6489bcaa-472b-433c-a430-bf7fa2eac814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::div[2]</value>
      <webElementGuid>fe9e3be9-b69c-474f-9014-993e503e08fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create AI Edit']/parent::*</value>
      <webElementGuid>a691b203-adb8-4b0a-9544-3d1daca0a762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>a15d041f-858f-4caf-884a-387549bb3ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create AI Edit' or . = 'Create AI Edit')]</value>
      <webElementGuid>daa4e295-d30c-461f-99f0-901c4431f5ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
