<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NEWEST TO OLDEST</name>
   <tag></tag>
   <elementGuidId>2fee2086-6069-4035-b949-a3da2ddea5cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='soft_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#soft_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#soft_type >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6908519c-a2a5-476c-8070-836684f7a1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sort-by show-desktop</value>
      <webElementGuid>4dc66d01-9496-408c-bd0a-511b3d7261ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>soft_type</value>
      <webElementGuid>654d961c-f3a6-417a-8335-f86d0568f80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>soft_type</value>
      <webElementGuid>04e2a589-f7c7-4d21-8ba4-2b28183f31ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEWEST TO OLDESTOLDEST TO NEWEST</value>
      <webElementGuid>505ce6d7-4623-4d50-8a0d-e8bfa627a53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-ai-edit&quot;]/div[2]/div[1]/div[@class=&quot;content&quot;]/div[1]/select[@id=&quot;soft_type&quot;]</value>
      <webElementGuid>135f6a17-2a96-4275-a277-71ca1f2f3782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='soft_type']</value>
      <webElementGuid>2148a83a-dc73-4e43-b771-1a3dbe13bc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>ac01e95e-dfd1-4933-a773-3dfa13da4a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::select[1]</value>
      <webElementGuid>7141c233-091b-47bc-9109-3a289eed4dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::select[1]</value>
      <webElementGuid>e0f8fbe7-5250-48a0-ab6a-6163364fe750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beta'])[1]/preceding::select[4]</value>
      <webElementGuid>f71e8483-a7d8-4837-b3af-4961cdec6def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start AI Edit'])[1]/preceding::select[4]</value>
      <webElementGuid>e0cea955-a255-458a-b350-0c3089cac888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>22186f8e-7a1b-4739-9270-84ba6a78cb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'soft_type' and @name = 'soft_type' and (text() = 'NEWEST TO OLDESTOLDEST TO NEWEST' or . = 'NEWEST TO OLDESTOLDEST TO NEWEST')]</value>
      <webElementGuid>123c6a55-5a89-497a-8a61-c1c81cd3ce2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
