<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALL</name>
   <tag></tag>
   <elementGuidId>e6438c72-fefc-4b52-adeb-ecd6f7ff5cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='soft_type'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#soft_type >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ffc41b3-9e3f-4c76-9fd8-89d05c621da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sort-by show-desktop</value>
      <webElementGuid>c9a1399b-1ffe-4cb9-bad5-c0f19bfa5e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>soft_type</value>
      <webElementGuid>46b6c682-59c2-4a10-ac11-1cccfe731125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>soft_type</value>
      <webElementGuid>09ba90cc-9485-4384-87b1-2f0df7b538f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLIN PROGRESSCONVERTED</value>
      <webElementGuid>4c494e26-50e6-422d-ba40-a32d0ac898b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-ai-edit&quot;]/div[2]/div[1]/div[@class=&quot;content&quot;]/div[1]/select[@id=&quot;soft_type&quot;]</value>
      <webElementGuid>719aee98-dbe8-49a0-ada2-7ee8cbeaa65e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='soft_type'])[3]</value>
      <webElementGuid>50cabe1e-a607-44f6-8d48-279ced8c1c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/div[2]/div/div/div/select[3]</value>
      <webElementGuid>33c90edf-fdf9-42a6-82c6-a03aa76b1da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::select[3]</value>
      <webElementGuid>cd30e75c-b29a-49b6-9f2e-7fcf9cd64a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::select[3]</value>
      <webElementGuid>09cd6288-8204-48f6-8541-a83c22571d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beta'])[1]/preceding::select[2]</value>
      <webElementGuid>ed4fabca-0f2b-4a97-afcf-21d0aaeb5d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start AI Edit'])[1]/preceding::select[2]</value>
      <webElementGuid>38405a20-17eb-4ba3-84d1-2a20a7e65b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>afee05ec-2143-47a9-a167-81f4cb6dac6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'soft_type' and @name = 'soft_type' and (text() = 'ALLIN PROGRESSCONVERTED' or . = 'ALLIN PROGRESSCONVERTED')]</value>
      <webElementGuid>2b01e969-adea-45aa-9010-cf12fd0fdaf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
