<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close Dialog_box</name>
   <tag></tag>
   <elementGuidId>5159ac31-2901-4f28-ba69-7d111e7c4349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Don't show this again&quot;i >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a82cc47f-2834-42c6-a04a-672271f328e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>adedb6cd-daa3-4b60-acad-e4aa9a47a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ai-edit-modal-container current-step-1 modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ai-edit-modal-container&quot;]/div[1]/div[@class=&quot;introduce-ai-panel&quot;]/div[@class=&quot;d-flex action-panel&quot;]/div[1]/div[@class=&quot;checkbox-section&quot;]/label[@class=&quot;ipt-label&quot;]/span[@class=&quot;box&quot;]</value>
      <webElementGuid>e13d5976-ca40-430b-be02-1fb1be42f3a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/span</value>
      <webElementGuid>a9b76fc6-d410-4757-8e9d-ff2a747328de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
