<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Console streamers image (1)</name>
   <tag></tag>
   <elementGuidId>23512f1c-5012-4ab9-9112-233bf04e3b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.elementor-element.elementor-element-de964b5.elementor-widget-mobile__width-initial.eael-infobox-shape-square.eael-infobox-hover-img-shape-square.elementor-widget.elementor-widget-eael-info-box > div.elementor-widget-container > a > div.eael-infobox.icon-on-left > div.infobox-icon > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://eklipse.gg/wp-content/uploads/2024/02/Console-Logo.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Console Streamers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7815f899-ba3e-4f3b-9948-a243ea41d5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eklipse.gg/wp-content/uploads/2024/02/Console-Logo.svg</value>
      <webElementGuid>34788137-8e2e-496a-becd-520dce2ec5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--center&quot;]/nav[@class=&quot;header-main__menu&quot;]/ul[@class=&quot;primary-menu&quot;]/li[@class=&quot;nav_item menu-item-depth-0 has-child menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children megamenu&quot;]/ul[@class=&quot;submenu submenu-lv1&quot;]/li[@class=&quot;megamenu&quot;]/div[@class=&quot;elementor elementor-11943&quot;]/div[@class=&quot;elementor-element elementor-element-e79b4d5 e-flex e-con-boxed e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-0f961dc e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-802d54d e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-de964b5 elementor-widget-mobile__width-initial eael-infobox-shape-square eael-infobox-hover-img-shape-square elementor-widget elementor-widget-eael-info-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/div[@class=&quot;eael-infobox icon-on-left&quot;]/div[@class=&quot;infobox-icon&quot;]/img[1]</value>
      <webElementGuid>47c24bcb-7abe-4375-884c-5b670d5829df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://eklipse.gg/wp-content/uploads/2024/02/Console-Logo.svg')]</value>
      <webElementGuid>2b8fbc6a-6e44-4ab5-a8ba-9da65f944081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a/div/div/img</value>
      <webElementGuid>2cc80f5a-e0c3-4a8c-9c44-ad72ceecf78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://eklipse.gg/wp-content/uploads/2024/02/Console-Logo.svg']</value>
      <webElementGuid>2f83feae-2226-4fe3-b024-e2e139d93f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
