<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gaming stream image</name>
   <tag></tag>
   <elementGuidId>f481d01d-a6d7-4087-af2b-885fc241b668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail.wp-image-12001</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Gaming-Stream_150px.png?resize=150%2C150&amp;ssl=1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.elementor-image-box-img > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bfdf191b-814d-4c61-a1b8-96ce9994eacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>8ea7675e-a55e-4d98-a98e-13954782f2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>b74f2d3a-6a0a-4b49-8e17-11b1f17cfa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Gaming-Stream_150px.png?resize=150%2C150&amp;ssl=1</value>
      <webElementGuid>c7160529-2376-4a4f-85ec-810e7030a47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail wp-image-12001</value>
      <webElementGuid>0bd8ceea-edf3-4998-a179-30030066dfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--center&quot;]/nav[@class=&quot;header-main__menu&quot;]/ul[@class=&quot;primary-menu&quot;]/li[@class=&quot;nav_item menu-item-depth-0 has-child menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children megamenu&quot;]/ul[@class=&quot;submenu submenu-lv1&quot;]/li[1]/div[@class=&quot;elementor elementor-11934&quot;]/div[@class=&quot;elementor-element elementor-element-e79b4d5 e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-8f4d5bc e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-d94e4cb e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-1c0d477 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-1ea88d9 elementor-position-left elementor-position-left elementor-vertical-align-middle elementor-widget__width-initial elementor-widget-mobile__width-initial elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/a[1]/img[@class=&quot;attachment-thumbnail size-thumbnail wp-image-12001&quot;]</value>
      <webElementGuid>97a4f4a6-5968-4ce6-87d1-02e1f767d503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Gaming-Stream_150px.png?resize=150%2C150&amp;ssl=1')]</value>
      <webElementGuid>39561655-1cca-4044-b824-cf5bb7bcf3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/a/img</value>
      <webElementGuid>d7acdd45-7728-46dc-bdab-39d98ae5c983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2024/02/Gaming-Stream_150px.png?resize=150%2C150&amp;ssl=1']</value>
      <webElementGuid>625a3e2d-7138-4601-a8f7-51ff8386cc25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
