<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>How to YouTube image</name>
   <tag></tag>
   <elementGuidId>33da3471-4972-4ca0-ad46-6c589930b218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail.wp-image-12939</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/youtube-logo.max-1000x1000_gd5NIq9.webp?resize=150%2C150&amp;ssl=1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Discovery Blog What is Eklipse.gg?Complete guide on how Eklipse can take your ch&quot;i >> img >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15eab8c5-a8a0-482b-aed3-df5825a82f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>327295ce-890e-4763-a01a-796dc1f51dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>c3e96f01-e2f5-4279-b29e-47106ac03b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>9b31acad-e414-47e7-8584-8e9ac1d4dd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/youtube-logo.max-1000x1000_gd5NIq9.webp?resize=150%2C150&amp;ssl=1</value>
      <webElementGuid>8ff7e5c5-0720-4054-aa72-e43bfc0203ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail wp-image-12939</value>
      <webElementGuid>986bcd7e-24aa-4332-b9ef-f4f411bfc855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--center&quot;]/nav[@class=&quot;header-main__menu&quot;]/ul[@class=&quot;primary-menu&quot;]/li[@class=&quot;nav_item menu-item-depth-0 has-child menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children megamenu&quot;]/ul[@class=&quot;submenu submenu-lv1&quot;]/li[1]/div[@class=&quot;elementor elementor-3789&quot;]/div[@class=&quot;elementor-element elementor-element-2add0a43 e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-8f16397 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-34055c5 elementor-position-left elementor-position-top elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-vertical-align-top elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/img[@class=&quot;attachment-thumbnail size-thumbnail wp-image-12939&quot;]</value>
      <webElementGuid>2ff92786-1f37-43f8-999b-8336136c3884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/youtube-logo.max-1000x1000_gd5NIq9.webp?resize=150%2C150&amp;ssl=1')]</value>
      <webElementGuid>865a5d93-cd81-4788-8145-b8e1734c079c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/figure/img</value>
      <webElementGuid>42cc84c7-8dc2-4f8e-8566-21311fb9446a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/12/youtube-logo.max-1000x1000_gd5NIq9.webp?resize=150%2C150&amp;ssl=1']</value>
      <webElementGuid>0fcc1ad6-cf0e-4837-b748-5fb65ed3a71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
