<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Features_logo-desktop</name>
   <tag></tag>
   <elementGuidId>eff0f700-f7ff-4365-9f23-610fd0209310</elementGuidId>
   <imagePath>../../OneDrive/Dokument/Tita/Lamaran kerja/Eklipse.gg/Eklipse.gg logo.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../OneDrive/Dokument/Tita/Lamaran kerja/Eklipse.gg/Eklipse.gg logo.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-desktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Eklipse']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1' and @alt = 'Eklipse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link[name=&quot;Eklipse&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af118dad-d160-4e1a-86af-0b517484dffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-desktop</value>
      <webElementGuid>1847a613-e342-42cc-b048-50889cdef665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1</value>
      <webElementGuid>f26e2261-cb3f-4907-be2a-6a679d3ad5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eklipse</value>
      <webElementGuid>0970dbe5-c0c3-469d-aaaa-aba2cc8afa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--left&quot;]/div[@class=&quot;header-main__logo&quot;]/a[1]/img[@class=&quot;logo-desktop&quot;]</value>
      <webElementGuid>27746208-16de-49c9-8f50-252c684a055e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eklipse']</value>
      <webElementGuid>1bf0ccf1-3077-4229-94a0-453938ef4a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a22879c1-05b4-4a18-930b-60b5e5c177f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1' and @alt = 'Eklipse']</value>
      <webElementGuid>bf869692-57c9-4386-b43a-a741639db7e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
