<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Features_logo-mobile</name>
   <tag></tag>
   <elementGuidId>28035313-74b8-461d-b6bf-7c3da1405701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Eklipse'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link[name=&quot;Eklipse&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>555d6411-9263-4595-a747-22a7295703a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-mobile</value>
      <webElementGuid>f781f859-1755-454d-927f-5e6fdf687731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eklipse.gg/wp-content/uploads/2022/09/Mask-group.png</value>
      <webElementGuid>9ba892b8-f400-4e32-be3f-6271d9eb80e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eklipse</value>
      <webElementGuid>ac6e5792-6df3-4cb5-9624-05b8baa807d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--left&quot;]/div[@class=&quot;header-main__logo&quot;]/a[1]/img[@class=&quot;logo-mobile&quot;]</value>
      <webElementGuid>2bdafab1-5f43-4adc-ba9b-6de627852b64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Eklipse'])[2]</value>
      <webElementGuid>185ac846-256e-403e-a837-54d309d008ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img[2]</value>
      <webElementGuid>3b749dac-8ea9-4898-aa98-6126180d0dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://eklipse.gg/wp-content/uploads/2022/09/Mask-group.png' and @alt = 'Eklipse']</value>
      <webElementGuid>752c0fd5-b471-422b-af16-7a18fad28d3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
