<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video reviews 389</name>
   <tag></tag>
   <elementGuidId>31d31da8-6bc3-4be6-9bd8-77faa2b09a58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.elementor-video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>video</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>dbdc17d6-cc3c-4fa2-b62a-3ab7191490d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-video</value>
      <webElementGuid>3370c53d-fd1c-434e-bdd8-12c4fa470267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>skrien-podatocen-ivzor</name>
      <type>Main</type>
      <value>https://dhf62eo10occ1.cloudfront.net/assets/LP-Short-White-Low-BR.mp4</value>
      <webElementGuid>3412caf3-5708-4711-bf2b-d2213ae966f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>muted</name>
      <type>Main</type>
      <value>muted</value>
      <webElementGuid>cab13562-92e9-4555-ad87-fe311ef921f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>8a976793-4f86-4c2c-9c38-16adca8766b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dhf62eo10occ1.cloudfront.net/assets/LP-Short-White-Low-BR.mp4</value>
      <webElementGuid>e29c58ed-120b-4c0c-a88a-e0f23b44347c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/main[1]/div[@class=&quot;elementor elementor-13271&quot;]/div[@class=&quot;elementor-element elementor-element-6e1f56c e-con-full e-flex e-con e-parent e-lazyloaded&quot;]/div[@class=&quot;elementor-element elementor-element-b0ff75c e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-9ee8331 elementor-widget__width-initial elementor-widget elementor-widget-video&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;e-hosted-video elementor-wrapper elementor-open-inline&quot;]/div[@class=&quot;mrzliv-polnac-vraper&quot;]/video[@class=&quot;elementor-video&quot;]</value>
      <webElementGuid>1d14e37c-2d42-4016-825c-88cd618e6b6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>01a549f9-8347-43b5-993d-c3146e183ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://dhf62eo10occ1.cloudfront.net/assets/LP-Short-White-Low-BR.mp4']</value>
      <webElementGuid>2e37e1be-b0f3-4b3e-8735-70751ec7ab9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
